"""E-56 and E-57's repairs, pinned (ADR-068).

Two independent repairs, tested independently:

- **E-56** — completeness is two quantities. The regression case is the discovery
  domain's calcination: rank **1 of 7** with a surviving-subspace gain of **14.44**, an
  operator that satisfies Core §3.4's dimension clause as completely as the rank
  criterion admits and violates its gain clause by more than an order of magnitude.
- **E-57** — Core §3.9's condition (a) has a precondition. Without a sufficiency deficit
  for the declared state the bound is **refused, not assumed**.

Assertions are on the qualitative claims and the orderings, per CLAUDE.md §7; the values
are recorded via `observe` and regenerated by `scripts/run_v15_part6_gate.py`.
"""

from __future__ import annotations

import numpy as np
import pytest

from omi.erasure import (
    ErasureCompleteness,
    ErrorControlVerdict,
    StateSufficiencyEvidence,
    condition_a_claim,
    measure_erasure,
)
from omi.operators import Control
from omi.state import Ensemble, Metric, State

from omi_domains.flagship.build import build_incoming_ensemble as build_flagship
from omi_domains.flagship.operators import HEATING_AND_SOAK
from omi_domains.flagship.state import FLAGSHIP_SCHEMA
from omi_domains.sdl.build import (
    CALCINATION_HOLD,
    CALCINATION_TEMPERATURE,
    build_chain,
    build_incoming_ensemble,
    sample_attainable_compositions,
)
from omi_domains.sdl.operators import Calcination
from omi_domains.sdl.state import SDL_SCHEMA
from tests.conftest import ObservationRecorder

ERASURE_RTOL = 1.0e-2
"""Declared relative rank tolerance, matching `tests/test_sdl_operators.py`. Required for
the same reason E-19 gives: at ADR-017's machine-epsilon default this spectrum reads full
rank and the erasure is invisible."""

N_FORMULATIONS = 80

GAIN_SEPARATOR = 5.0
"""A loose separator between a decaying erasure's gain and an amplifying one.

Deliberately loose and declared rather than inlined: what the tests assert is that the two
domains sit on opposite sides of unity by a comfortable margin, not that either gain takes
a particular value (CLAUDE.md §7)."""


@pytest.fixture(scope="module")
def calcination_completeness() -> ErasureCompleteness:
    """The E-56 regression case, measured on the incoming population across formulations.

    Across formulations rather than within one, because with a single composition every
    component except pore accessibility is constant by construction and the declared metric
    would be degenerate (CLAUDE.md invariant 1's "incoming population").
    """
    rng = np.random.default_rng(4)
    compositions = sample_attainable_compositions(N_FORMULATIONS, rng)
    support = build_incoming_ensemble(N_FORMULATIONS, rng)
    rows = [
        build_chain(composition, 0)
        .rollout(Ensemble(SDL_SCHEMA, support.particles[i][None, :]))
        .ensembles[1]
        .particles[0]
        for i, composition in enumerate(compositions)
    ]
    population = Ensemble(SDL_SCHEMA, np.stack(rows))
    control = Control(0.0, CALCINATION_HOLD, lambda t: np.array([CALCINATION_TEMPERATURE]))
    measurement = measure_erasure(
        Calcination(composition=compositions[0]),
        State(SDL_SCHEMA, population.particles.mean(axis=0)),
        control,
        Metric.from_ensemble(population),
        rtol=ERASURE_RTOL,
    )
    return measurement.completeness()


# --- E-56 -------------------------------------------------------------------


def test_the_two_clauses_of_the_erasure_definition_come_apart(
    calcination_completeness: ErasureCompleteness, observe: ObservationRecorder
) -> None:
    """**The E-56 regression case.** Core §3.4 joins "image of substantially lower
    effective dimension" and ``L ≪ 1`` as one definition. This operator satisfies the
    first and violates the second.

    Asserted qualitatively: the rank collapses to one direction, and the gain on that
    direction exceeds unity. The *value* `14.44` is metric-dependent (E-33's territory) and
    is recorded rather than pinned.
    """
    observe("erasure_effective_rank", calcination_completeness.effective_rank, "== 1")
    observe("erasure_state_dimension", calcination_completeness.state_dimension, "== 7")
    observe("erasure_surviving_gain", calcination_completeness.surviving_gain, "> 1.0")
    observe("erasure_erased_gain", calcination_completeness.erased_gain, "<< 1")
    observe("erasure_completeness_summary", calcination_completeness.summary(), "states both clauses")

    assert calcination_completeness.dimension_collapsed, "the declared erasure erases nothing"
    assert not calcination_completeness.gain_contracted, (
        "this test exists to record that the declared erasure AMPLIFIES its surviving "
        "direction; if that stops being true, E-56 needs re-measuring, not deleting"
    )
    assert calcination_completeness.effective_rank == 1
    assert calcination_completeness.state_dimension == SDL_SCHEMA.size
    assert calcination_completeness.erased_gain < calcination_completeness.surviving_gain


def test_completeness_refuses_to_be_a_single_verdict(
    calcination_completeness: ErasureCompleteness,
) -> None:
    """The mechanical half of the repair: a caller cannot collapse the two quantities.

    Synthesising a combined score would bake E-56's own conflation into this repository,
    so the object raises instead. That is the whole reason `__bool__` exists.
    """
    with pytest.raises(TypeError, match="no single truth value"):
        bool(calcination_completeness)
    with pytest.raises(TypeError, match="E-56"):
        if calcination_completeness:  # pragma: no cover - the raise is the assertion
            pass


def test_a_decaying_erasure_satisfies_both_clauses(observe: ObservationRecorder) -> None:
    """The contrasting case, so the repair is not merely a way of failing flagship too.

    Flagship's `HEATING_AND_SOAK` erases by exponential decay of two state components, and
    both of Core §3.4's clauses hold there — which is why eleven milestones of erasure
    measurement did not surface E-56. Measured at a declared tolerance that admits the
    decayed directions as erased.
    """
    rng = np.random.default_rng(0)
    ensemble = build_flagship(64, rng)
    control = Control(0.0, 1.0, lambda t: np.array([1123.0, 0.0]))
    measurement = measure_erasure(
        HEATING_AND_SOAK,
        State(FLAGSHIP_SCHEMA, ensemble.particles.mean(axis=0)),
        control,
        Metric.from_ensemble(ensemble),
        rtol=ERASURE_RTOL,
    )
    completeness = measurement.completeness()

    observe("flagship_erasure_rank", completeness.effective_rank, f"< {FLAGSHIP_SCHEMA.size}")
    observe("flagship_erasure_surviving_gain", completeness.surviving_gain, "<= ~1")
    observe("flagship_erasure_summary", completeness.summary(), "both clauses stated")

    assert completeness.dimension_collapsed, "flagship's declared erasure should erase something"
    assert completeness.surviving_gain < GAIN_SEPARATOR, (
        "flagship's erasure should not amplify the way calcination does; that contrast is "
        "what makes E-56 a finding about the definition rather than about one domain"
    )


# --- E-57 -------------------------------------------------------------------


def test_condition_a_is_refused_when_the_declared_state_is_untested(
    calcination_completeness: ErasureCompleteness, observe: ObservationRecorder
) -> None:
    """E-57's repair, in its default case.

    With no deficit supplied the bound is **refused**, and the refusal names the reason.
    Note this operator is refused on the *gain* clause first, which is E-56 and E-57
    interacting exactly as the ordered diagnosis intends: the first thing that blocks is
    reported, not a list.
    """
    claim = condition_a_claim(calcination_completeness)
    observe("condition_a_verdict_calcination", claim.verdict.name, "REFUSED_GAIN_NOT_CONTRACTED")
    observe("condition_a_reason_calcination", claim.reason, "names the gain, not the deficit")

    assert not claim.claimable
    assert claim.verdict is ErrorControlVerdict.REFUSED_GAIN_NOT_CONTRACTED


def test_a_contracting_erasure_is_still_refused_without_a_deficit(
    observe: ObservationRecorder,
) -> None:
    """The case E-57 is really about: **both** clauses of §3.4 hold, and condition (a) is
    still not claimable, because a state-space erasure cannot bound error from a variable
    outside the state space and nothing has tested whether one exists.

    Constructed rather than taken from a domain, so the two clauses are known to hold by
    construction and the only thing missing is the deficit."""
    contracting = ErasureCompleteness(
        effective_rank=2,
        state_dimension=7,
        tolerance=1.0e-3,
        surviving_gain=0.4,
        erased_gain=1.0e-6,
        metric=Metric(FLAGSHIP_SCHEMA, np.ones(FLAGSHIP_SCHEMA.size)),
    )
    assert contracting.dimension_collapsed and contracting.gain_contracted

    refused = condition_a_claim(contracting)
    observe("condition_a_verdict_untested", refused.verdict.name, "REFUSED_STATE_UNTESTED")
    assert refused.verdict is ErrorControlVerdict.REFUSED_STATE_UNTESTED
    assert "outside the state space" in refused.reason

    tested = condition_a_claim(
        contracting,
        StateSufficiencyEvidence(
            deficit_squared=1.0e-4, threshold=1.0e-2, provenance="matched pairs at depth 6, oracle"
        ),
    )
    observe("condition_a_verdict_tested", tested.verdict.name, "CLAIMABLE")
    assert tested.claimable

    insufficient = condition_a_claim(
        contracting,
        StateSufficiencyEvidence(
            deficit_squared=1.0, threshold=1.0e-2, provenance="matched pairs at depth 6, oracle"
        ),
    )
    observe("condition_a_verdict_insufficient", insufficient.verdict.name, "REFUSED_DEFICIT_ABOVE_THRESHOLD")
    assert insufficient.verdict is ErrorControlVerdict.REFUSED_DEFICIT_ABOVE_THRESHOLD


def test_evidence_without_provenance_is_not_evidence() -> None:
    """A deficit value with no statement of what produced it cannot support the
    precondition — the same discipline ADR-043 applies to a validity range."""
    with pytest.raises(ValueError, match="provenance"):
        StateSufficiencyEvidence(deficit_squared=0.0, threshold=1.0, provenance="   ")
