"""Readouts for the flagship chain (Core §7.1).

``AggregateHardness`` (Type-0, Class A) is deliberately defined *in terms of*
the Type-1 constitutive operator, not as separate duplicated arithmetic —
this is Core §2.6's "properties are functionals of the constitutive operator
alone" made literal in code.
"""

from __future__ import annotations

from dataclasses import dataclass, field

import numpy as np

from omi.operators import Control
from omi.readouts import ConstitutiveOperator, ConstitutiveReadout, FunctionalReadout, ReadoutClass
from omi.state import FloatArray, Slot, State

_NULL_CONTROL = Control(0.0, 1.0, lambda t: np.array([0.0]))


@dataclass(frozen=True)
class HardnessConstitutiveOperator(ConstitutiveOperator):
    """Bound to a state; carries the hardening memory (``accumulated_hardening``
    in ``z``) and maps a subsequent driving programme to a hardness response
    and an updated state (Core §3.5, Type-1)."""

    state: State
    base_hardness: float = 100.0
    inclusion_weight: float = 5.0
    grain_size_weight: float = 20.0
    hardening_weight: float = 2.0
    hardening_rate: float = 0.5

    def respond(self, control: Control) -> tuple[FloatArray, State]:
        s = self.state
        inclusion = s.get(Slot.Z, "inclusion_content")[0]
        grain_size = s.get(Slot.M, "prior_grain_size")[0]
        hardening = s.get(Slot.Z, "accumulated_hardening")[0]
        u = control(control.t0)[0]
        dt = control.duration

        new_hardening = hardening + self.hardening_rate * abs(u) * dt
        response = (
            self.base_hardness
            + self.inclusion_weight * inclusion
            + self.grain_size_weight / (1.0 + abs(grain_size))
            + self.hardening_weight * new_hardening
        )
        updated = s.with_component(Slot.Z, "accumulated_hardening", np.array([new_hardening]))
        return np.array([response]), updated


@dataclass(frozen=True)
class ExtractHardness(ConstitutiveReadout):
    """Core §3.5, Type-1: extracts the hardness constitutive operator implied
    by a state."""

    def __call__(self, state: State) -> HardnessConstitutiveOperator:
        return HardnessConstitutiveOperator(state=state)


@dataclass(frozen=True)
class AggregateHardness(FunctionalReadout):
    """Core §3.5, Type-0; Core §2.6: a property, hence a functional of the
    constitutive operator alone — computed by calling
    :class:`ExtractHardness` with a null (zero-driving) control, so no
    additional hardening accrues and the arithmetic is not duplicated
    between the Type-0 and Type-1 readouts."""

    readout_class: ReadoutClass = field(default=ReadoutClass.A)

    def evaluate(self, state: State) -> FloatArray:
        operator = ExtractHardness()(state)
        response, _ = operator.respond(_NULL_CONTROL)
        return response

    def jacobian(self, state: State) -> FloatArray:
        """Exact analytic Jacobian (ADR-001): closed-form derivative of the
        null-control response, rather than a finite-difference estimate —
        used as a target readout for observability triage."""
        jac = np.zeros((1, state.schema.size))
        inclusion_weight = 5.0
        grain_size_weight = 20.0
        hardening_weight = 2.0
        grain_size = state.get(Slot.M, "prior_grain_size")[0]
        sign = 1.0 if grain_size >= 0 else -1.0
        jac[0, state.schema.slice_for(Slot.Z, "inclusion_content")] = inclusion_weight
        jac[0, state.schema.slice_for(Slot.M, "prior_grain_size")] = (
            -grain_size_weight * sign / (1.0 + abs(grain_size)) ** 2
        )
        jac[0, state.schema.slice_for(Slot.Z, "accumulated_hardening")] = hardening_weight
        return jac


@dataclass(frozen=True)
class ForceTorqueSensor(FunctionalReadout):
    """In-die force/torque sensing (Core §7.1's observation suite item;
    Core §3.8's proposition: integrated response signals generated by the
    apparatus itself are Type-0 readouts of the constitutive response and
    therefore direct observations of ``z``). Reads ``substructure_density``,
    the sub-resolution quantity actively contracting during heating."""

    readout_class: ReadoutClass = field(default=ReadoutClass.A)

    def evaluate(self, state: State) -> FloatArray:
        return state.get(Slot.Z, "substructure_density")

    def jacobian(self, state: State) -> FloatArray:
        jac = np.zeros((1, state.schema.size))
        jac[0, state.schema.slice_for(Slot.Z, "substructure_density")] = 1.0
        return jac


@dataclass(frozen=True)
class CoatingGauge(FunctionalReadout):
    """Coating thickness gauge (Core §7.1's observation suite item): a
    direct, exact readout of the surviving ``Γ`` component."""

    readout_class: ReadoutClass = field(default=ReadoutClass.A)

    def evaluate(self, state: State) -> FloatArray:
        return state.get(Slot.GAMMA, "coating_thickness")

    def jacobian(self, state: State) -> FloatArray:
        jac = np.zeros((1, state.schema.size))
        jac[0, state.schema.slice_for(Slot.GAMMA, "coating_thickness")] = 1.0
        return jac
