"""Readouts for the flagship chain (Core §7.1).

``AggregateHardness`` (Type-0, Class A) is deliberately defined *in terms of*
the Type-1 constitutive operator, not as separate duplicated arithmetic —
this is Core §2.6's "properties are functionals of the constitutive operator
alone" made literal in code.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from typing import Callable

import numpy as np

from omi.operators import Control
from omi.readouts import (
    ComponentReadout,
    ConstitutiveOperator,
    ConstitutiveReadout,
    FunctionalReadout,
    ReadoutClass,
    Type2Geometry,
)
from omi.state import FloatArray, Slot, State

_NULL_CONTROL = Control(0.0, 1.0, lambda t: np.array([0.0]))

N_THROUGH_THICKNESS_QUADRATURE_POINTS = 9
"""Odd, so the neutral axis (z=0, zero strain) is itself a quadrature point
— Tier I½'s through-thickness quadrature (ADR-035, docs/DECISIONS.md), not a
mesh: a fixed, small number of direct evaluations along one axis."""


def _constant_strain_fn(value: float) -> Callable[[float], FloatArray]:
    def fn(t: float) -> FloatArray:
        return np.array([value])

    return fn


@dataclass(frozen=True)
class HardnessConstitutiveOperator(ConstitutiveOperator):
    """Bound to a state; carries the hardening memory (``accumulated_hardening``
    in ``z``) and maps a subsequent driving programme to a hardness response
    and an updated state (Core §3.5, Type-1)."""

    state: State
    base_hardness: float = 100.0
    inclusion_weight: float = 5.0
    grain_size_weight: float = 20.0
    hardening_weight: float = 2.0
    hardening_rate: float = 0.5

    def respond(self, control: Control) -> tuple[FloatArray, State]:
        s = self.state
        inclusion = s.get(Slot.Z, "inclusion_content")[0]
        grain_size = s.get(Slot.M, "prior_grain_size")[0]
        hardening = s.get(Slot.Z, "accumulated_hardening")[0]
        u = control(control.t0)[0]
        dt = control.duration

        new_hardening = hardening + self.hardening_rate * abs(u) * dt
        response = (
            self.base_hardness
            + self.inclusion_weight * inclusion
            + self.grain_size_weight / (1.0 + abs(grain_size))
            + self.hardening_weight * new_hardening
        )
        updated = s.with_component(Slot.Z, "accumulated_hardening", np.array([new_hardening]))
        return np.array([response]), updated


@dataclass(frozen=True)
class ExtractHardness(ConstitutiveReadout):
    """Core §3.5, Type-1: extracts the hardness constitutive operator implied
    by a state."""

    def __call__(self, state: State) -> HardnessConstitutiveOperator:
        return HardnessConstitutiveOperator(state=state)


@dataclass(frozen=True)
class AggregateHardness(FunctionalReadout):
    """Core §3.5, Type-0; Core §2.6: a property, hence a functional of the
    constitutive operator alone — computed by calling
    :class:`ExtractHardness` with a null (zero-driving) control, so no
    additional hardening accrues and the arithmetic is not duplicated
    between the Type-0 and Type-1 readouts."""

    readout_class: ReadoutClass = field(default=ReadoutClass.A)

    def evaluate(self, state: State) -> FloatArray:
        operator = ExtractHardness()(state)
        response, _ = operator.respond(_NULL_CONTROL)
        return response

    def jacobian(self, state: State) -> FloatArray:
        """Exact analytic Jacobian (ADR-001): closed-form derivative of the
        null-control response, rather than a finite-difference estimate —
        used as a target readout for observability triage."""
        jac = np.zeros((1, state.schema.size))
        inclusion_weight = 5.0
        grain_size_weight = 20.0
        hardening_weight = 2.0
        grain_size = state.get(Slot.M, "prior_grain_size")[0]
        sign = 1.0 if grain_size >= 0 else -1.0
        jac[0, state.schema.slice_for(Slot.Z, "inclusion_content")] = inclusion_weight
        jac[0, state.schema.slice_for(Slot.M, "prior_grain_size")] = (
            -grain_size_weight * sign / (1.0 + abs(grain_size)) ** 2
        )
        jac[0, state.schema.slice_for(Slot.Z, "accumulated_hardening")] = hardening_weight
        return jac


@dataclass(frozen=True)
class ForceTorqueSensor(FunctionalReadout):
    """In-die force/torque sensing (Core §7.1's observation suite item;
    Core §3.8's proposition: integrated response signals generated by the
    apparatus itself are Type-0 readouts of the constitutive response and
    therefore direct observations of ``z``). Reads ``substructure_density``,
    the sub-resolution quantity actively contracting during heating."""

    readout_class: ReadoutClass = field(default=ReadoutClass.A)

    def evaluate(self, state: State) -> FloatArray:
        return state.get(Slot.Z, "substructure_density")

    def jacobian(self, state: State) -> FloatArray:
        jac = np.zeros((1, state.schema.size))
        jac[0, state.schema.slice_for(Slot.Z, "substructure_density")] = 1.0
        return jac


@dataclass(frozen=True)
class CoatingGauge(FunctionalReadout):
    """Coating thickness gauge (Core §7.1's observation suite item): a
    direct, exact readout of the surviving ``Γ`` component."""

    readout_class: ReadoutClass = field(default=ReadoutClass.A)

    def evaluate(self, state: State) -> FloatArray:
        return state.get(Slot.GAMMA, "coating_thickness")

    def jacobian(self, state: State) -> FloatArray:
        jac = np.zeros((1, state.schema.size))
        jac[0, state.schema.slice_for(Slot.GAMMA, "coating_thickness")] = 1.0
        return jac


@dataclass(frozen=True)
class BendAngle(ComponentReadout):
    """Tier I½'s concrete instance (ADR-035, docs/DECISIONS.md): bending, the
    Type-2/Class-B response Core §7.1's own table declares for the flagship
    and which no Type-2 readout has ever existed to supply.

    Linear through-thickness strain, ``ε(z) = curvature · z`` for
    ``z ∈ [-thickness/2, thickness/2]`` — the one loading mode ADR-035
    permits — drives the *existing* Type-1 constitutive operator
    (:class:`HardnessConstitutiveOperator`) at
    :data:`N_THROUGH_THICKNESS_QUADRATURE_POINTS` points spanning the
    thickness: :meth:`~omi.readouts.ConstitutiveOperator.respond` is called
    once per point from the *same* bound operator (a frozen dataclass;
    ``respond`` does not mutate it), so each point is an independent
    evaluation from the same initial state, not a sequential time history.
    The outer-fibre value (``|z|`` maximal, where bending strain peaks) is
    the returned response; the thickness fraction where the local response
    exceeds :attr:`driver_threshold` — Spec §4.1's declared critical value
    ``D_c``, a property of when local hardening indicates incipient
    cracking, not a statistic of any particular campaign's data — is the
    process-zone volume Core §3.6's Class B claim couples the tiers
    through.
    """

    readout_class: ReadoutClass = field(default=ReadoutClass.B)
    driver_threshold: float = 106.3
    """``D_c`` (Spec §4.1): calibrated once against a nominal
    (mean-inclusion-content, unit-geometry) specimen so a typical specimen
    shows a modest, non-degenerate process zone near the outer fibre —
    declared here, not fit inside `omi.classb` (Core §4 item 4b)."""
    n_quadrature_points: int = N_THROUGH_THICKNESS_QUADRATURE_POINTS

    def evaluate(
        self, operator: ConstitutiveOperator, geometry: Type2Geometry
    ) -> tuple[FloatArray, float]:
        z = np.linspace(-geometry.thickness / 2.0, geometry.thickness / 2.0, self.n_quadrature_points)
        strain = geometry.curvature * z
        driver_field = np.empty(self.n_quadrature_points)
        for i, eps in enumerate(strain):
            control = Control(0.0, 1.0, _constant_strain_fn(float(eps)))
            response, _updated_state = operator.respond(control)
            driver_field[i] = response[0]

        outer_fibre_response = float(np.max(driver_field))
        process_zone_fraction = float(np.mean(driver_field > self.driver_threshold))
        process_zone_volume = process_zone_fraction * geometry.thickness
        return np.array([outer_fibre_response]), process_zone_volume
